# Generated by Django 5.2.7 on 2025-11-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField()),
                ("preview", models.ImageField(blank=True, null=True, upload_to="blog_images/", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("count_of_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
        ),
    ]
