# Generated by Django 5.2.7 on 2025-11-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["title", "created_at"], "verbose_name": "пост", "verbose_name_plural": "посты"},
        ),
    ]
