# Generated by Django 5.2.7 on 2025-11-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="count_of_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
