# Generated by Django 5.2.7 on 2025-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_count_of_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Контент"),
        ),
    ]
