# Generated by Django 5.2.7 on 2025-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Наименование организации")),
                ("email", models.CharField(max_length=100, verbose_name="Электронная почта")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ["name"],
            },
        ),
    ]
