# Generated by Django 5.2.7 on 2025-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
