# Generated by Django 4.2.26 on 2025-11-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
